namespace Dnet.Blazor.Components.Overlay.Infrastructure.Interfaces
{
    public class CSSStyleDeclaration
    {
        public string AlignContent { get; set; }
        public string AlignItems { get; set; }
        public string AlignSelf { get; set; }
        public string AlignmentBaseline { get; set; }
        public string Animation { get; set; }
        public string AnimationDelay { get; set; }
        public string AnimationDirection { get; set; }
        public string AnimationDuration { get; set; }
        public string AnimationFillMode { get; set; }
        public string AnimationIterationCount { get; set; }
        public string AnimationName { get; set; }
        public string AnimationPlayState { get; set; }
        public string AnimationTimingFunction { get; set; }
        public string BackfaceVisibility { get; set; }
        public string Background { get; set; }
        public string BackgroundAttachment { get; set; }
        public string BackgroundClip { get; set; }
        public string BackgroundColor { get; set; }
        public string BackgroundImage { get; set; }
        public string BackgroundOrigin { get; set; }
        public string BackgroundPosition { get; set; }
        public string BackgroundPositionX { get; set; }
        public string BackgroundPositionY { get; set; }
        public string BackgroundRepeat { get; set; }
        public string BackgroundSize { get; set; }
        public string BaselineShift { get; set; }
        public string BlockSize { get; set; }
        public string Border { get; set; }
        public string BorderBlockEnd { get; set; }
        public string BorderBlockEndColor { get; set; }
        public string BorderBlockEndStyle { get; set; }
        public string BorderBlockEndWidth { get; set; }
        public string BorderBlockStart { get; set; }
        public string BorderBlockStartColor { get; set; }
        public string BorderBlockStartStyle { get; set; }
        public string BorderBlockStartWidth { get; set; }
        public string BorderBottom { get; set; }
        public string BorderBottomColor { get; set; }
        public string BorderBottomLeftRadius { get; set; }
        public string BorderBottomRightRadius { get; set; }
        public string BorderBottomStyle { get; set; }
        public string BorderBottomWidth { get; set; }
        public string BorderCollapse { get; set; }
        public string BorderColor { get; set; }
        public string BorderImage { get; set; }
        public string BorderImageOutset { get; set; }
        public string BorderImageRepeat { get; set; }
        public string BorderImageSlice { get; set; }
        public string BorderImageSource { get; set; }
        public string BorderImageWidth { get; set; }
        public string BorderInlineEnd { get; set; }
        public string BorderInlineEndColor { get; set; }
        public string BorderInlineEndStyle { get; set; }
        public string BorderInlineEndWidth { get; set; }
        public string BorderInlineStart { get; set; }
        public string BorderInlineStartColor { get; set; }
        public string BorderInlineStartStyle { get; set; }
        public string BorderInlineStartWidth { get; set; }
        public string BorderLeft { get; set; }
        public string BorderLeftColor { get; set; }
        public string BorderLeftStyle { get; set; }
        public string BorderLeftWidth { get; set; }
        public string BorderRadius { get; set; }
        public string BorderRight { get; set; }
        public string BorderRightColor { get; set; }
        public string BorderRightStyle { get; set; }
        public string BorderRightWidth { get; set; }
        public string BorderSpacing { get; set; }
        public string BorderStyle { get; set; }
        public string BorderTop { get; set; }
        public string BorderTopColor { get; set; }
        public string BorderTopLeftRadius { get; set; }
        public string BorderTopRightRadius { get; set; }
        public string BorderTopStyle { get; set; }
        public string BorderTopWidth { get; set; }
        public string BorderWidth { get; set; }
        public string Bottom { get; set; }
        public string BoxShadow { get; set; }
        public string BoxSizing { get; set; }
        public string BreakAfter { get; set; }
        public string BreakBefore { get; set; }
        public string BreakInside { get; set; }
        public string CaptionSide { get; set; }
        public string CaretColor { get; set; }
        public string Clear { get; set; }
        public string Clip { get; set; }
        public string ClipPath { get; set; }
        public string ClipRule { get; set; }
        public string Color { get; set; }
        public string ColorInterpolation { get; set; }
        public string ColorInterpolationFilters { get; set; }
        public string ColumnCount { get; set; }
        public string ColumnFill { get; set; }
        public string ColumnGap { get; set; }
        public string ColumnRule { get; set; }
        public string ColumnRuleColor { get; set; }
        public string ColumnRuleStyle { get; set; }
        public string ColumnRuleWidth { get; set; }
        public string ColumnSpan { get; set; }
        public string ColumnWidth { get; set; }
        public string Columns { get; set; }
        public string Content { get; set; }
        public string CounterIncrement { get; set; }
        public string CounterReset { get; set; }
        public string CssFloat { get; set; }
        public string CssText { get; set; }
        public string Cursor { get; set; }
        public string Direction { get; set; }
        public string Display { get; set; }
        public string DominantBaseline { get; set; }
        public string EmptyCells { get; set; }
        public string EnableBackground { get; set; }
        public string Fill { get; set; }
        public string FillOpacity { get; set; }
        public string FillRule { get; set; }
        public string Filter { get; set; }
        public string Flex { get; set; }
        public string FlexBasis { get; set; }
        public string FlexDirection { get; set; }
        public string FlexFlow { get; set; }
        public string FlexGrow { get; set; }
        public string FlexShrink { get; set; }
        public string FlexWrap { get; set; }
        public string Float { get; set; }
        public string FloodColor { get; set; }
        public string FloodOpacity { get; set; }
        public string Font { get; set; }
        public string FontFamily { get; set; }
        public string FontFeatureSettings { get; set; }
        public string FontKerning { get; set; }
        public string FontSize { get; set; }
        public string FontSizeAdjust { get; set; }
        public string FontStretch { get; set; }
        public string FontStyle { get; set; }
        public string FontSynthesis { get; set; }
        public string FontVariant { get; set; }
        public string FontVariantCaps { get; set; }
        public string FontVariantEastAsian { get; set; }
        public string FontVariantLigatures { get; set; }
        public string FontVariantNumeric { get; set; }
        public string FontVariantPosition { get; set; }
        public string FontWeight { get; set; }
        public string Gap { get; set; }
        public string GlyphOrientationHorizontal { get; set; }
        public string GlyphOrientationVertical { get; set; }
        public string Grid { get; set; }
        public string GridArea { get; set; }
        public string GridAutoColumns { get; set; }
        public string GridAutoFlow { get; set; }
        public string GridAutoRows { get; set; }
        public string GridColumn { get; set; }
        public string GridColumnEnd { get; set; }
        public string GridColumnGap { get; set; }
        public string GridColumnStart { get; set; }
        public string GridGap { get; set; }
        public string GridRow { get; set; }
        public string GridRowEnd { get; set; }
        public string GridRowGap { get; set; }
        public string GridRowStart { get; set; }
        public string GridTemplate { get; set; }
        public string GridTemplateAreas { get; set; }
        public string GridTemplateColumns { get; set; }
        public string GridTemplateRows { get; set; }
        public string Height { get; set; }
        public string Hyphens { get; set; }
        public string ImageOrientation { get; set; }
        public string ImageRendering { get; set; }
        public string ImeMode { get; set; }
        public string InlineSize { get; set; }
        public string JustifyContent { get; set; }
        public string JustifyItems { get; set; }
        public string JustifySelf { get; set; }
        public string Kerning { get; set; }
        public string LayoutGrid { get; set; }
        public string LayoutGridChar { get; set; }
        public string LayoutGridLine { get; set; }
        public string LayoutGridMode { get; set; }
        public string LayoutGridType { get; set; }
        public string Left { get; set; }
        public int Length { get; set; }
        public string LetterSpacing { get; set; }
        public string LightingColor { get; set; }
        public string LineBreak { get; set; }
        public string LineHeight { get; set; }
        public string ListStyle { get; set; }
        public string ListStyleImage { get; set; }
        public string ListStylePosition { get; set; }
        public string ListStyleType { get; set; }
        public string Margin { get; set; }
        public string MarginBlockEnd { get; set; }
        public string MarginBlockStart { get; set; }
        public string MarginBottom { get; set; }
        public string MarginInlineEnd { get; set; }
        public string MarginInlineStart { get; set; }
        public string MarginLeft { get; set; }
        public string MarginRight { get; set; }
        public string MarginTop { get; set; }
        public string Marker { get; set; }
        public string MarkerEnd { get; set; }
        public string MarkerMid { get; set; }
        public string MarkerStart { get; set; }
        public string Mask { get; set; }
        public string MaskComposite { get; set; }
        public string MaskImage { get; set; }
        public string MaskPosition { get; set; }
        public string MaskRepeat { get; set; }
        public string MaskSize { get; set; }
        public string MaskType { get; set; }
        public string MaxBlockSize { get; set; }
        public string MaxHeight { get; set; }
        public string MaxInlineSize { get; set; }
        public string MaxWidth { get; set; }
        public string MinBlockSize { get; set; }
        public string MinHeight { get; set; }
        public string MinInlineSize { get; set; }
        public string MinWidth { get; set; }
        public string MsContentZoomChaining { get; set; }
        public string MsContentZoomLimit { get; set; }
        public string MsContentZoomLimitMax { get; set; }
        public string MsContentZoomLimitMin { get; set; }
        public string MsContentZoomSnap { get; set; }
        public string MsContentZoomSnapPoints { get; set; }
        public string MsContentZoomSnapType { get; set; }
        public string MsContentZooming { get; set; }
        public string MsFlowFrom { get; set; }
        public string MsFlowInto { get; set; }
        public string MsFontFeatureSettings { get; set; }
        public string MsGridColumn { get; set; }
        public string MsGridColumnAlign { get; set; }
        public string MsGridColumnSpan { get; set; }
        public string MsGridColumns { get; set; }
        public string MsGridRow { get; set; }
        public string MsGridRowAlign { get; set; }
        public string MsGridRowSpan { get; set; }
        public string MsGridRows { get; set; }
        public string MsHighContrastAdjust { get; set; }
        public string MsHyphenateLimitChars { get; set; }
        public string MsHyphenateLimitLines { get; set; }
        public string MsHyphenateLimitZone { get; set; }
        public string MsHyphens { get; set; }
        public string MsImeAlign { get; set; }
        public string MsOverflowStyle { get; set; }
        public string MsScrollChaining { get; set; }
        public string MsScrollLimit { get; set; }
        public string MsScrollLimitXMax { get; set; }
        public string MsScrollLimitXMin { get; set; }
        public string MsScrollLimitYMax { get; set; }
        public string MsScrollLimitYMin { get; set; }
        public string MsScrollRails { get; set; }
        public string MsScrollSnapPointsX { get; set; }
        public string MsScrollSnapPointsY { get; set; }
        public string MsScrollSnapType { get; set; }
        public string MsScrollSnapX { get; set; }
        public string MsScrollSnapY { get; set; }
        public string MsScrollTranslation { get; set; }
        public string MsTextCombineHorizontal { get; set; }
        public string MsTextSizeAdjust { get; set; }
        public string MsTouchAction { get; set; }
        public string MsTouchSelect { get; set; }
        public string MsUserSelect { get; set; }
        public string MsWrapFlow { get; set; }
        public string MsWrapMargin { get; set; }
        public string MsWrapThrough { get; set; }
        public string ObjectFit { get; set; }
        public string ObjectPosition { get; set; }
        public string Opacity { get; set; }
        public string Order { get; set; }
        public string Orphans { get; set; }
        public string Outline { get; set; }
        public string OutlineColor { get; set; }
        public string OutlineOffset { get; set; }
        public string OutlineStyle { get; set; }
        public string OutlineWidth { get; set; }
        public string Overflow { get; set; }
        public string OverflowAnchor { get; set; }
        public string OverflowWrap { get; set; }
        public string OverflowX { get; set; }
        public string OverflowY { get; set; }
        public string Padding { get; set; }
        public string PaddingBlockEnd { get; set; }
        public string PaddingBlockStart { get; set; }
        public string PaddingBottom { get; set; }
        public string PaddingInlineEnd { get; set; }
        public string PaddingInlineStart { get; set; }
        public string PaddingLeft { get; set; }
        public string PaddingRight { get; set; }
        public string PaddingTop { get; set; }
        public string PageBreakAfter { get; set; }
        public string PageBreakBefore { get; set; }
        public string PageBreakInside { get; set; }
        public string PaintOrder { get; set; }
        public string PenAction { get; set; }
        public string Perspective { get; set; }
        public string PerspectiveOrigin { get; set; }
        public string PlaceContent { get; set; }
        public string PlaceItems { get; set; }
        public string PlaceSelf { get; set; }
        public string PointerEvents { get; set; }
        public string Position { get; set; }
        public string Quotes { get; set; }
        public string Resize { get; set; }
        public string Right { get; set; }
        public string Rotate { get; set; }
        public string RowGap { get; set; }
        public string RubyAlign { get; set; }
        public string RubyOverhang { get; set; }
        public string RubyPosition { get; set; }
        public string Scale { get; set; }
        public string ScrollBehavior { get; set; }
        public string ShapeRendering { get; set; }
        public string StopColor { get; set; }
        public string StopOpacity { get; set; }
        public string Stroke { get; set; }
        public string StrokeDasharray { get; set; }
        public string StrokeDashoffset { get; set; }
        public string StrokeLinecap { get; set; }
        public string StrokeLinejoin { get; set; }
        public string StrokeMiterlimit { get; set; }
        public string StrokeOpacity { get; set; }
        public string StrokeWidth { get; set; }
        public string TabSize { get; set; }
        public string TableLayout { get; set; }
        public string TextAlign { get; set; }
        public string TextAlignLast { get; set; }
        public string TextAnchor { get; set; }
        public string TextCombineUpright { get; set; }
        public string TextDecoration { get; set; }
        public string TextDecorationColor { get; set; }
        public string TextDecorationLine { get; set; }
        public string TextDecorationStyle { get; set; }
        public string TextEmphasis { get; set; }
        public string TextEmphasisColor { get; set; }
        public string TextEmphasisPosition { get; set; }
        public string TextEmphasisStyle { get; set; }
        public string TextIndent { get; set; }
        public string TextJustify { get; set; }
        public string TextKashida { get; set; }
        public string TextKashidaSpace { get; set; }
        public string TextOrientation { get; set; }
        public string TextOverflow { get; set; }
        public string TextRendering { get; set; }
        public string TextShadow { get; set; }
        public string TextTransform { get; set; }
        public string TextUnderlinePosition { get; set; }
        public string Top { get; set; }
        public string TouchAction { get; set; }
        public string Transform { get; set; }
        public string TransformBox { get; set; }
        public string TransformOrigin { get; set; }
        public string TransformStyle { get; set; }
        public string Transition { get; set; }
        public string TransitionDelay { get; set; }
        public string TransitionDuration { get; set; }
        public string TransitionProperty { get; set; }
        public string TransitionTimingFunction { get; set; }
        public string Translate { get; set; }
        public string UnicodeBidi { get; set; }
        public string UserSelect { get; set; }
        public string VerticalAlign { get; set; }
        public string Visibility { get; set; }
        public string WebkitColumnBreakAfter { get; set; }
        public string WebkitColumnBreakBefore { get; set; }
        public string WebkitColumnBreakInside { get; set; }
        public string WebkitColumnCount { get; set; }
        public string WebkitColumnGap { get; set; }
        public string WebkitColumnRule { get; set; }
        public string WebkitColumnRuleColor { get; set; }
        public string WebkitColumnRuleStyle { get; set; }
        public string WebkitColumnRuleWidth { get; set; }
        public string WebkitColumnSpan { get; set; }
        public string WebkitColumnWidth { get; set; }
        public string WebkitColumns { get; set; }
        public string WebkitUserModify { get; set; }
        public string WebkitUserSelect { get; set; }
        public string WebkitWritingMode { get; set; }
        public string WhiteSpace { get; set; }
        public string Widows { get; set; }
        public string Width { get; set; }
        public string WillChange { get; set; }
        public string WordBreak { get; set; }
        public string WordSpacing { get; set; }
        public string WordWrap { get; set; }
        public string WritingMode { get; set; }
        public string ZIndex { get; set; }
        public string Zoom { get; set; }
    }
}
